version: '3.4'

services:
  concerto.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 7000:80
      - 7001:443
    volumes:
      - ~/.aspnet/https:/https:ro
