version: '3.4'

volumes:
  postgres_data:
      driver: local
  pgadmin_data:
  keycloak_data:
  concerto_files:

services:
  concerto.server:
    image: etav/concerto_server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 7000:80
      - 7001:443
    env_file:
      - concerto.env
    volumes:
      - concerto_files:/var/lib/concerto/storage

  postgres:
      image: postgres:15.0
      container_name: Postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - postgres.env
      ports:
        - 5432:5432

  keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      container_name: Keycloak
      env_file:
        - keycloak.env
      ports:
        - 7200:8080
        - 7201:8443
      depends_on:
        - postgres
      volumes:
        - keycloak_data:/var/lib/keycloak/data
      command: start-dev