version: '3.4'

volumes:
  postgres_data:
      driver: local
  pgadmin_data:
  keycloak_data:
  concerto_files:

services:
  concerto.server:
    image: etav/concerto_server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 7000:80  # Port 7000 widoczny dla swiata zewnętrznego
      - 7001:443 # Port 7001 widoczny dla swiata zewnętrznego
    env_file:
      - concerto.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - concerto_files:/var/lib/concerto/storage

  postgres:
      image: postgres:15.0
      container_name: Postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - postgres.env

  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      container_name: Keycloak
      env_file:
        - keycloak.env
      ports:
        - 7200:8080 # Port 7200 widoczny dla swiata zewnętrznego
        - 7201:8443 # Port 7201 widoczny dla swiata zewnętrznego
      depends_on:
        - postgres
      volumes:
        - keycloak_data:/var/lib/keycloak/data
      command: start-dev