version: '3.4'

volumes:
  postgres_data:
      driver: local

services:
  concerto.server:
    image: etav/concertoserver
    ports:
      - 7000:80
      - 7001:443
    environment:
      ASPNETCORE_DOCKER: "true"
      DB_STRING: "Host=postgres;Port=5432;Database=ConcertoDb;username=admin;Password=admin"

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - 5432:5432

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "7100:80"

  keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 7200:8080
        - 7201:8443
      depends_on:
        - postgres
      command: start-dev