version: '3.4'

volumes:
  postgres_data:
      driver: local
  pgadmin_data:
  keycloak_data:

services:
  concerto.server:
    image: ${DOCKER_REGISTRY-}concertoserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 7000:80
      - 7001:443
    environment:
      ASPNETCORE_DOCKER: true
      ASPNETCORE_REMOTE: true
      DB_STRING: "Host=postgres;Port=5432;Database=ConcertoDb;username=admin;Password=admin"

  postgres:
      image: postgres:15.0
      container_name: Postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - 5432:5432

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "7100:80"

  keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      command: -c standalone.xml
      container_name: Keycloak
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        # JDBC_PARAMS: "ssl=true"
      ports:
        - 7200:8080
        - 7201:8443
      depends_on:
        - postgres
      volumes:
        - keycloak_data:/var/lib/keycloak/data
      command: start-dev